// lib/firebase_options.dart
//
// Generated by `flutterfire configure` against the CLIENT's Firebase
// project (ar-science-explorer-57de3), NOT the dev's own separate
// ar-science-explorer project (different project ID, same display name --
// see PROJECT_HANDOVER.md for why there are two). Do not edit by hand —
// re-run `flutterfire configure` if these values ever need to change.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show kIsWeb, TargetPlatform, defaultTargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          '${defaultTargetPlatform.name} is not a supported platform for this app.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF4gQBfW2s0kAKX3UqdO2q_8TiOS4fejo',
    appId: '1:462322623597:web:7354f77d159fa6f15e0b64',
    messagingSenderId: '462322623597',
    projectId: 'ar-science-explorer-57de3',
    authDomain: 'ar-science-explorer-57de3.firebaseapp.com',
    storageBucket: 'ar-science-explorer-57de3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwEF6q7HCQYWJbmuXzb3E6qVk5t6ZyFdw',
    appId: '1:462322623597:android:14fe9fc1b9b6eda65e0b64',
    messagingSenderId: '462322623597',
    projectId: 'ar-science-explorer-57de3',
    storageBucket: 'ar-science-explorer-57de3.firebasestorage.app',
  );
}
