plugins {
    id("com.android.application")
    // START: FlutterFire Configuration
    id("com.google.gms.google-services")
    // END: FlutterFire Configuration
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "com.arscience.ar_science_explorer"
    // Matches unityLibrary/gradle.properties' unity.compileSdkVersion —
    // flutter.compileSdkVersion could resolve lower than what the exported
    // Unity library was built against.
    compileSdk = 36
    // flutter_embed_unity (Phase 3 AR Lab): must be >= unityLibrary's own
    // unity.androidNdkVersion (see android/unityLibrary/gradle.properties),
    // not flutter.ndkVersion, which can resolve to an older version Unity
    // 6000.4.0f1's export wasn't built against.
    ndkVersion = "27.2.12479018"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.arscience.ar_science_explorer"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        // flutter_embed_unity (Phase 3 AR Lab): must be >= unityLibrary's own
        // unity.minSdkVersion=29 (see android/unityLibrary/gradle.properties)
        // — flutter.minSdkVersion resolves lower and causes a manifest merge
        // failure against the exported Unity library.
        minSdk = maxOf(flutter.minSdkVersion, 29)
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    // flutter_embed_unity (Phase 3 AR Lab): prevents double-compressing
    // Unity's already-compressed resource files, which otherwise
    // significantly slows down Unity's load time inside the embed.
    androidResources {
        val unityStreamingAssetsList = (project.findProperty("unityStreamingAssets") as? String)
            ?.split(",")
            ?.map { it.trim() }
            ?: emptyList()

        noCompress += listOf(
            ".unity3d", ".ress", ".resource", ".obb", ".bundle", ".unityexp"
        ) + unityStreamingAssetsList

        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }
}

dependencies {
    // flutter_embed_unity (Phase 3 AR Lab): the exported Unity Android
    // library (see android/unityLibrary/, generated by Unity's own
    // "Flutter Embed -> Export project to Flutter app" menu item).
    implementation(project(":unityLibrary"))
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
